-- Migration number: 0001 generated by teenybase on 2026-02-17T14:06:08.077Z. Do not modify this file.

CREATE TABLE couples (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	inviter_id TEXT NOT NULL REFERENCES users(id), 
	partner_id TEXT REFERENCES users(id), 
	invite_code TEXT UNIQUE NOT NULL, 
	status TEXT NOT NULL DEFAULT "pending"
);
CREATE INDEX idx_couples_inviter_id ON couples (inviter_id);
CREATE INDEX idx_couples_partner_id ON couples (partner_id);
CREATE INDEX idx_couples_invite_code ON couples (invite_code);
CREATE TRIGGER tgr_couples_raise_on_created_update BEFORE UPDATE OF created ON couples BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;