-- Migration number: 0002 generated by teenybase on 2026-02-17T14:06:08.077Z. Do not modify this file.

CREATE TABLE swipes (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	user_id TEXT NOT NULL REFERENCES users(id), 
	couple_id TEXT NOT NULL REFERENCES couples(id), 
	tmdb_id INTEGER NOT NULL, 
	media_type TEXT NOT NULL DEFAULT "movie", 
	direction TEXT NOT NULL
);
CREATE INDEX idx_swipes_user_id ON swipes (user_id);
CREATE INDEX idx_swipes_couple_id ON swipes (couple_id);
CREATE INDEX idx_swipes_tmdb_id ON swipes (tmdb_id);
CREATE TRIGGER tgr_swipes_raise_on_created_update BEFORE UPDATE OF created ON swipes BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;