-- Migration number: 0003 generated by teenybase on 2026-02-17T14:06:08.077Z. Do not modify this file.

CREATE TABLE matches (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	couple_id TEXT NOT NULL REFERENCES couples(id), 
	tmdb_id INTEGER NOT NULL, 
	media_type TEXT NOT NULL DEFAULT "movie", 
	movie_data JSON NOT NULL, 
	watched BOOLEAN DEFAULT 0
);
CREATE INDEX idx_matches_couple_id ON matches (couple_id);
CREATE INDEX idx_matches_tmdb_id ON matches (tmdb_id);
CREATE TRIGGER tgr_matches_raise_on_created_update BEFORE UPDATE OF created ON matches BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;