-- Migration number: 0004 generated by teenybase on 2026-02-17T14:06:08.078Z. Do not modify this file.

CREATE TABLE user_services (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	user_id TEXT NOT NULL REFERENCES users(id), 
	services JSON NOT NULL
);
CREATE INDEX idx_user_services_user_id ON user_services (user_id);
CREATE TRIGGER tgr_user_services_raise_on_created_update BEFORE UPDATE OF created ON user_services BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;