-- Migration number: 0005 generated by teenybase on 2026-02-17T14:06:08.078Z. Do not modify this file.

CREATE TABLE kv_store (
	key TEXT PRIMARY KEY NOT NULL, 
	value JSON NOT NULL, 
	expire TIMESTAMP
);